# these are executed in order.  each must pass for the next to be run
stages:
  - lint
  - test
  - deploy

# defaults
language: node_js
node_js: '10'
# disable automatic npm install
install: true

jobs:
  include:
    - stage: lint
      script: bash .travis/script.sh install lint
      node_js: '10'

    - &node
      stage: test
      script: bash .travis/script.sh install build test
      node_js: '8'

    - <<: *node
      node_js: '6'

    - <<: *node
      node_js: '4'

    - <<: *node
      node_js: '0.12'

      # coverage includes testing, thats why 10 is not in test stage
    - stage: deploy
      script: bash .travis/script.sh install build coverage deploy
      node_js: '10'

env:
  global:
    secure: "V5h4IJT+Hyj8NxWHLwPuSW6wsrfUwNmtp4QXIgP2uHTgcwtFFC8vi+NAbGN/n3LQxxY3t6wukH0aACZIynX5MBYpwfIHWUlipnYn8uPPLpxrwxb18C6hTBDxMtq4gaBJGsAZWJI7WcoPG81KIH32mz8TMbuKHx6yw331Cjt7W019yFOu7D1nx7TOAy4GZJUkmkkQKfbSReQwFW6ilaPwf+HaxxytdRLbFPYuP2gp3qxR4zgYR6MqBP/EHaw63j7G+7euSDXm7or5uebkoQqbqcmedpVy3mDe04mV/b33OgsS+zfTXRzODVW9Bfl+Krtis6Y7BpR/O9ID5gMX+g86BZgDWuCgEe+qIFM/IJZ/bFC+g5xhERDr516VXlgYoc6K1FZmWvFGsp1z25/cnEXMC6+C/xkHT8UYQAt7XZFchsE7IMSoC7W/WErmN+A5tgFD2mvtA9tm9RvkGnReqTmtGQD/hI4DEaRcy8UzIZBUfA6jy9w5T45P1R6nHOsP2TJ+UeV/lcXXge/mSDZk0Uy3vRRWUcM0rq9KiasN5bF4YYA4ziDlLtGLWEReMATaFbU8ieeRZYaUYPLqw2GGgCm5ExG5uJfI/Eh/2UMYNLnBTNcQ2W+HSJwgAMzmuqlU5sp896V44ovWtOp2MeGC2gOCcj0w1ZDqakyUbRgDiy2xHNg="
