# these are executed in order.  each must pass for the next to be run
stages:
  - lint
  - test
  - deploy

# defaults
language: node_js
node_js: '10'
# disable automatic npm install
install: true

_test_stage: &_test_stage
  stage: test
  script: bash .travis/script.sh install build test

jobs:
  include:
    - stage: lint
      script: bash .travis/script.sh install lint
      node_js: '10'

    - <<: *_test_stage
      node_js: '8'

    - <<: *_test_stage
      node_js: '6'

    - <<: *_test_stage
      node_js: '4'

    - <<: *_test_stage
      node_js: '0.12'

      # coverage includes testing, thats why 10 is not in test stage
    - stage: deploy
      script: bash .travis/script.sh install build coverage deploy
      node_js: '10'

env:
  global:
    secure: nzlvXMSCAy6xB3RxDfFJTE8c0eP9LsK45/d77+AeXCTywI5yIpAAnXhfRBwpAVsiug8sPGgPPJ7jla4sCuecxUfLXBoQ/0foPlBEgt/mEUeGEZev6rBV0HE6GU5MSUi/Z/lv0YOTqzbC66MSos4yNivmWPJHe37KfDMWdjT2M2ogTGu9aQAfyCRlVnKcpR08s54M4wdU2joTpiIn1UCupgYm6ELAG6j9Ch394Z5T7Yz7MD29Ht3oyupM3T2hvN/KGYcyROyXE+dIVxr/hWC2KT6CpJXWJvZQcgCD0CXwJySNOgmIhdvB5gSG2fYT4MqNuiFjVZlSi+was0l5u98wE6oVRKkWmQgdbBIygEir71iUaQHSSCNT18FZRu/0r2FHXvD3A4fdxXwK4KXo9xl9LfK/zvCPSwGhodEIxYzjwEEFkKqd9FndzOV2zdD+QFyid4vl7GT2eG4UYL5BT594MlLxVMDHslGbLIM8EhPOBnZ3cVTBjx4chkU1CpWCykaNYcFNa8yMqLH4zbQsy1462VrF8vTa9QfAYfU3zdOjBLE3AC/fKHIra0soqh4iC8prYnRmxkcXavAFR2Lsb9z20qLZA2JuVxYl8Q1FUjAWcVS38E0OkRQb7PXm/LabA3rxBzG0YdyHBgC1CZtXEOJ9U0SrZiXGu+iqSrdB4YCVcaA=
